#!/usr/bin/env bash
# Configure make.conf, fstab, locale, timezone, portage settings
set -euo pipefail

LOG_DIR="/var/log/turbogentoo"
LOG_FILE="${LOG_DIR}/02-base-config.log"

TG_MOUNTROOT="${TG_MOUNTROOT:-/mnt/gentoo}"
TG_HOSTNAME="${TG_HOSTNAME:-gentoo}"
TG_TIMEZONE="${TG_TIMEZONE:-Europe/Moscow}"
TG_LOCALE="${TG_LOCALE:-en_US.UTF-8}"
TG_USE_BINPKG="${TG_USE_BINPKG:-1}"
TG_CFLAGS="${TG_CFLAGS:--O2 -pipe -march=native}"
TG_WM="${TG_WM:-i3}"
TG_PROFILE="${TG_PROFILE:-desktop}"
DRY_RUN="${DRY_RUN:-0}"

CYAN='\033[0;36m'; GREEN='\033[0;32m'; RED='\033[0;31m'
YELLOW='\033[1;33m'; BOLD='\033[1m'; RESET='\033[0m'

log() { echo -e "${CYAN}[$(date '+%H:%M:%S')]${RESET} $*" | tee -a "${LOG_FILE}"; }
ok()  { echo -e "${GREEN}[OK]${RESET} $*"  | tee -a "${LOG_FILE}"; }
die() { echo -e "${RED}[ERROR]${RESET} $*" | tee -a "${LOG_FILE}" >&2; exit 1; }

[[ "${EUID}" -eq 0 ]] || die "Must be run as root"
mkdir -p "${LOG_DIR}"
log "Base configuration started"

PARTMAP="${TG_MOUNTROOT}/turbogentoo-partmap.env"
[[ -f "${PARTMAP}" ]] && source "${PARTMAP}"

[[ -f "${TG_MOUNTROOT}/etc/gentoo-release" ]] || die "Stage3 not found at ${TG_MOUNTROOT}. Run 01-stage3-install.sh first."

# ── detect CPU count ──────────────────────────────────────────────────────────
CPU_CORES="$(nproc)"
MAKEOPTS_JOBS=$(( CPU_CORES + 1 ))
log "Detected ${CPU_CORES} CPU cores → MAKEOPTS=-j${MAKEOPTS_JOBS}"

# ── USE flags per profile ─────────────────────────────────────────────────────
use_flags_minimal="X alsa -bluetooth -gnome -kde -systemd minimal"
use_flags_desktop="X alsa bluetooth dbus udev -gnome -kde -systemd pulseaudio pipewire"
use_flags_dev="X alsa bluetooth dbus udev -gnome -kde -systemd pulseaudio pipewire git"

case "${TG_PROFILE}" in
    minimal) USE_FLAGS="${use_flags_minimal}" ;;
    desktop) USE_FLAGS="${use_flags_desktop}" ;;
    dev)     USE_FLAGS="${use_flags_dev}" ;;
    *)       USE_FLAGS="${use_flags_desktop}" ;;
esac

# WM-specific USE flags
case "${TG_WM}" in
    sway)    USE_FLAGS="${USE_FLAGS} wayland -X" ;;
    i3)      USE_FLAGS="${USE_FLAGS} X -wayland" ;;
    openbox) USE_FLAGS="${USE_FLAGS} X -wayland" ;;
esac

# ── write make.conf ───────────────────────────────────────────────────────────
write_make_conf() {
    local mc="${TG_MOUNTROOT}/etc/portage/make.conf"
    log "Writing ${mc}..."

    local binpkg_features=""
    if [[ "${TG_USE_BINPKG}" == "1" ]]; then
        binpkg_features='FEATURES="${FEATURES} getbinpkg binpkg-request-signature"'$'\n'
        binpkg_features+='PORTAGE_BINHOST="https://binpkgs.gentoo.org/packages/default/linux/amd64/17.1/"'
    fi

    cat > "${mc}" <<EOF
# Generated by TurboGentoo 02-base-config.sh
# $(date)

CFLAGS="${TG_CFLAGS}"
CXXFLAGS="\${CFLAGS}"
FCFLAGS="\${CFLAGS}"
FFLAGS="\${CFLAGS}"

MAKEOPTS="-j${MAKEOPTS_JOBS} -l${CPU_CORES}"
EMERGE_DEFAULT_OPTS="--jobs=${CPU_CORES} --load-average=${CPU_CORES} --ask=n --quiet-build"

USE="${USE_FLAGS}"

# Accepted licences
ACCEPT_LICENSE="-* @FREE @BINARY-REDISTRIBUTABLE"

# Keywords
ACCEPT_KEYWORDS="amd64"

# Language support — trim to what you actually need
L10N="en"
LINGUAS="en"

# Input devices
INPUT_DEVICES="libinput"

# Video cards — adjust to your GPU (amdgpu radeonsi / nvidia / intel i965)
VIDEO_CARDS="amdgpu radeonsi"

${binpkg_features}

# Portage mirrors
GENTOO_MIRRORS="${TG_MIRROR}"

# Portage temp on tmpfs for speed (requires enough RAM, ~2G per job)
# PORTAGE_TMPDIR="/tmp"

GRUB_PLATFORMS="efi-64"
EOF
    ok "make.conf written"
}

# ── fstab ─────────────────────────────────────────────────────────────────────
write_fstab() {
    local fstab="${TG_MOUNTROOT}/etc/fstab"
    log "Writing ${fstab}..."

    # Get UUIDs
    local root_uuid efi_uuid swap_uuid=""
    root_uuid="$(blkid -s UUID -o value "${TG_PART_ROOT}" 2>/dev/null || echo "FILL_ROOT_UUID")"
    if [[ -n "${TG_PART_EFI:-}" ]]; then
        efi_uuid="$(blkid -s UUID -o value "${TG_PART_EFI}" 2>/dev/null || echo "FILL_EFI_UUID")"
    fi
    if [[ -n "${TG_PART_SWAP:-}" ]]; then
        swap_uuid="$(blkid -s UUID -o value "${TG_PART_SWAP}" 2>/dev/null || echo "FILL_SWAP_UUID")"
    fi

    local fs_opts
    case "${TG_FS_ROOT:-ext4}" in
        ext4)  fs_opts="noatime,errors=remount-ro" ;;
        btrfs) fs_opts="noatime,compress=zstd,space_cache=v2" ;;
        xfs)   fs_opts="noatime,inode64" ;;
    esac

    {
        echo "# /etc/fstab — generated by TurboGentoo"
        echo "#"
        echo "# <fs>                                   <mp>       <type>  <opts>                   <dump> <pass>"
        echo "UUID=${root_uuid}  /          ${TG_FS_ROOT:-ext4}    ${fs_opts}    0      1"
        if [[ -n "${TG_PART_EFI:-}" ]]; then
            echo "UUID=${efi_uuid}  /boot/efi  vfat    umask=077                0      2"
        fi
        if [[ -n "${swap_uuid}" ]]; then
            echo "UUID=${swap_uuid}  none       swap    sw                       0      0"
        fi
        echo "tmpfs                                    /tmp       tmpfs   nosuid,nodev             0      0"
    } > "${fstab}"
    ok "fstab written"
}

# ── hostname ──────────────────────────────────────────────────────────────────
write_hostname() {
    log "Setting hostname to ${TG_HOSTNAME}..."
    echo "${TG_HOSTNAME}" > "${TG_MOUNTROOT}/etc/hostname"
    # Also write /etc/hosts
    cat > "${TG_MOUNTROOT}/etc/hosts" <<EOF
127.0.0.1   localhost
::1         localhost
127.0.1.1   ${TG_HOSTNAME}.localdomain ${TG_HOSTNAME}
EOF
    ok "Hostname set: ${TG_HOSTNAME}"
}

# ── timezone ──────────────────────────────────────────────────────────────────
write_timezone() {
    log "Setting timezone to ${TG_TIMEZONE}..."
    echo "${TG_TIMEZONE}" > "${TG_MOUNTROOT}/etc/timezone"
    # Will be finalised inside chroot via `emerge --config sys-libs/timezone-data`
    ok "Timezone set: ${TG_TIMEZONE}"
}

# ── locale ────────────────────────────────────────────────────────────────────
write_locale() {
    log "Setting locale to ${TG_LOCALE}..."
    cat > "${TG_MOUNTROOT}/etc/locale.gen" <<EOF
${TG_LOCALE} UTF-8
en_US.UTF-8 UTF-8
EOF
    ok "locale.gen written"
}

# ── portage repo config ───────────────────────────────────────────────────────
setup_portage() {
    log "Configuring portage repositories..."
    local repos_dir="${TG_MOUNTROOT}/etc/portage/repos.conf"
    mkdir -p "${repos_dir}"
    cp "${TG_MOUNTROOT}/usr/share/portage/config/repos.conf" \
       "${repos_dir}/gentoo.conf" 2>/dev/null || true

    # Copy our package.use / package.accept_keywords
    local script_dir
    script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
    if [[ -d "${script_dir}/configs/package.use" ]]; then
        cp -r "${script_dir}/configs/package.use/." \
              "${TG_MOUNTROOT}/etc/portage/package.use/"
    fi
    if [[ -d "${script_dir}/configs/package.accept_keywords" ]]; then
        cp -r "${script_dir}/configs/package.accept_keywords/." \
              "${TG_MOUNTROOT}/etc/portage/package.accept_keywords/"
    fi
    ok "Portage configured"
}

# ── mount pseudo-filesystems for chroot ───────────────────────────────────────
mount_pseudo() {
    log "Mounting pseudo-filesystems for chroot..."
    for fs in proc sys dev; do
        mountpoint -q "${TG_MOUNTROOT}/${fs}" && continue
        case "${fs}" in
            proc) mount -t proc proc "${TG_MOUNTROOT}/proc" ;;
            sys)  mount --rbind /sys "${TG_MOUNTROOT}/sys" && mount --make-rslave "${TG_MOUNTROOT}/sys" ;;
            dev)  mount --rbind /dev "${TG_MOUNTROOT}/dev" && mount --make-rslave "${TG_MOUNTROOT}/dev" ;;
        esac
    done
    ok "Pseudo-filesystems mounted"
}

# ── in-chroot configuration ───────────────────────────────────────────────────
chroot_configure() {
    log "Running in-chroot configuration..."
    chroot "${TG_MOUNTROOT}" /bin/bash -l <<'CHROOT_EOF'
set -euo pipefail

# Sync portage tree if not already synced
if [[ ! -d /var/db/repos/gentoo ]]; then
    emerge-webrsync
fi

# Configure timezone
emerge --config sys-libs/timezone-data 2>/dev/null || true

# Generate locales
locale-gen

# Set default locale
eselect locale set "$(locale -a | grep -i 'utf8\|utf-8' | grep -i 'en_us' | head -1 || echo 'en_US.utf8')"
env-update && source /etc/profile

echo "In-chroot configuration done"
CHROOT_EOF
    ok "Chroot configuration complete"
}

# ── main ──────────────────────────────────────────────────────────────────────
if [[ "${DRY_RUN}" == "1" ]]; then
    echo -e "${YELLOW}[DRY-RUN]${RESET} Would write make.conf, fstab, hostname, locale, timezone"
    exit 0
fi

write_make_conf
write_fstab
write_hostname
write_timezone
write_locale
setup_portage
mount_pseudo
chroot_configure

log "02-base-config.sh finished successfully"
echo
echo -e "${GREEN}${BOLD}Base config done. Next: bash scripts/03-kernel-setup.sh${RESET}"
